rabbitmq:
  image: rabbitmq:3.4
  ports:
    - "5672:5672"
notifier:
  build: .
  dockerfile: Dockerfile.notifier
  command: ./run_nodejs.sh
  volumes:
    - .:/app:z
  ports:
    - "3000:3000"
worker:
  build: .
  dockerfile: Dockerfile.server
  command: ./run_celery.sh
  volumes:
    - .:/app:z
  links:
    - rabbitmq
    - notifier
server:
  build: .
  dockerfile: Dockerfile.server
  command: ./run_webserver.sh
  volumes:
    - .:/app:z
  ports:
    - "5000:5000"
  links:
    - rabbitmq
    - notifier
